#!/bin/bash

# Check if the operating system is Arch Linux or Ubuntu
if cat /etc/os-release | grep -i "ID_LIKE" | grep -i "arch"; then
    # Install Docker on Arch Linux
    # sudo pacman -Syu
    sudo pacman -S --noconfirm docker xorg-xhost docker-compose

    sudo systemctl start docker.service
    sudo systemctl enable docker.service

    # Install Python and pip
    # sudo pacman -S --noconfirm python python-pip

elif cat /etc/os-release | grep -i "ID_LIKE" | grep -i "debian"; then
    # Install Docker on Ubuntu
    sudo apt-get update
    sudo apt-get install -y xorg x11-xserver-utils
    curl -fsSL https://get.docker.com | sh

    sudo systemctl start docker
    sudo systemctl enable docker
    sudo apt install python3 python3-pip
    sudo pip3 install docker-compose
fi

# Install Docker Compose using pip

# Add the current non-root user to the docker group
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker

mkdir -p /home/$USER/fluttercoder/config
mkdir -p /home/$USER/fluttercoder/projects


xhost +SI:localuser:$(whoami)


docker run -d --name fluttercoder2 --privileged \
    -v /dev/bus/usb:/dev/bus/usb \
    --network=host \
    --restart unless-stopped \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.Xauthority:/home/fluttercoder/.Xauthority \
    -e DISPLAY=$DISPLAY \
    -v /home/$USER/fluttercoder/projects:/home/fluttercoder/.local/share/code-server/User/workspace/tinder:z \
    -v /home/$USER/fluttercoder/config:/home/fluttercoder/.local/share/code-server/config:z \
    sonunigam4097/flutter-cdr:v4.0


read -p "Do you want to install Portainer, a program to manage your containers? (y/n)" choice
if [[ "$choice" =~ ^[Yy]$ ]]; then
    docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer
    echo "Portainer installed , now go to http://localhost:9000 to set portainer password, you must do it immediately"
else
    echo "Portainer not installed"
fi

# docker run -d --name  --privileged \
# -p 9801:8080 \
# -v /dev/bus/usb:/dev/bus/usb  \
# --restart unless-stopped \
# -v /home/$USER/fluttercoder/projects:/home/fluttercoder/.local/share/code-server/User/workspace/tinder:z \
# -v /home/$USER/fluttercoder/config:/home/fluttercoder/.local/share/code-server/config:z \
# sonunigam4097/fluttercoder:v3.1
